[library]
[library.HeatModel]
language = "c++"
library = "bmiheatcxx"
header = "bmi_heat.hxx"
entry_point = "BmiHeat"


[build]
undef_macros = []
define_macros = []
libraries = []
library_dirs = []
include_dirs = []
extra_compile_args = []

[package]
name = "pymt_heatcxx"
requirements = [""]

[info]
github_username = "pymt-lab"
package_author = "csdms"
package_author_email = "csdms@colorado.edu"
package_license = "MIT"
summary = "PyMT plugin for heatcxx model"


[ci]
python_version = ["3.9"]
os = ["linux", "mac", "windows"]

